kf.marquee=function(b,a){this.config={effect:"horizontal",overStop:true};if(a){$.extend(this.config,a);}if(typeof(b)=="object"){this.obj=b;}else{this.obj=$("#"+b);
}this.objWidth=this.obj.width();this.objHeight=this.obj.height();this.wrap=this.obj.find(".kf-marquee-wrap");this.content=this.wrap.find(".kf-marquee-content");
if(this.content.length==0){this.content=this.wrap.find("ul");}this.pannel=this.content.find(".kf-marquee-pannel");if(this.pannel.length==0){this.pannel=this.wrap.find("li");
}this.scrollState=false;this.scrollSize=0;this.stopState=false;this.init();};kf.marquee.prototype={init:function(){var a=this;this.cloneContent=this.content.clone();
this.doSize();if(this.pannel.find("img").length){this.pannel.find("img").each(function(){if(this.complete){a.doSize();}else{newImg.onload=function(){a.doSize();
};newImg.onerror=function(){a.doSize();};}});}if(this.config.overStop){this.obj.hover(function(){a.doStop();},function(){a.doPlay();});}},doSize:function(){var a=0;
if(this.config.effect=="vertical"){this.pannel.each(function(){a+=$(this).outerHeight();});this.content.height(a);this.cloneContent.height(a);this.wrap.height(a*2);
if(!this.scrollState&&a>this.objHeight){this.scrollState=true;this.wrap.append(this.cloneContent);this.cloneContent.height(a);this.doScroll();}}else{this.pannel.each(function(){a+=$(this).outerWidth();
});this.content.width(a);this.cloneContent.width(a);this.wrap.width(a*2);if(!this.scrollState&&a>this.objWidth){this.scrollState=true;this.wrap.append(this.cloneContent);
this.cloneContent.width(a);this.doScroll();}}this.scrollSize=a;},doScroll:function(){var b=this;if(!this.stopState){if(this.config.effect=="vertical"){var a=this.obj.scrollTop()+1;
if(a>=this.scrollSize){a=0;}this.obj.scrollTop(a);}else{var a=this.obj.scrollLeft()+1;if(a>=this.scrollSize){a=0;}this.obj.scrollLeft(a);}}setTimeout(function(){b.doScroll();
},10);},doStop:function(){this.stopState=true;},doPlay:function(){this.stopState=false;}};